### ISSUE TITLE
在Android 4.4的模拟器上面遇到的问题

### ISSUE THREAD

**Issue by Sonnyzoom** [bingoogolapple/BGASwipeBackLayout-Android#10]
![a](http://ofp4swv4i.bkt.clouddn.com/issues3.gif)
下面的布局会被顶起来，没有铺满屏幕，不知道是不是下面有虚拟键的原因，在4.4以上的系统就没问题。

**Comment by bingoogolapple** [comment]
不是这个库的问题，更 #9 同样的问题

**Comment by Sonnyzoom** [comment]
@bingoogolapple 但是我已经把StatusBarUtil这个库给删了，问题还存在呢

**Comment by bingoogolapple** [comment]
4.4 的真机上第一次设置 StatusBar 颜色时会出现底部多出 StatusBar 高度的空白区域，在 onStart 方法里连续设置两次 StatusBar 的颜色试试
