### ISSUE TITLE
nestedscrollview冲突

### ISSUE THREAD

**Issue by XuEnhao** [bingoogolapple/BGASwipeBackLayout-Android#118]
主布局是nestscrollview 跳转走后 测滑退出后 scrollview 会向上弹一定的距离

**Comment by codeingLiu** [comment]
> 主布局是nestscrollview 跳转走后 测滑退出后 scrollview 会向上弹一定的距离
我也遇到同样的问题，你怎么解决的

**Comment by XuEnhao** [comment]
我记得是焦点问题 记得是
