### ISSUE TITLE
Android P滑动返回界面闪烁问题(已解决)

### ISSUE THREAD

**Issue by Sopage** [bingoogolapple/BGASwipeBackLayout-Android#126]
追踪代码出现在退出动画中
即BGASwipeBackHelper中第245行中的executeSwipeBackAnim， 如何处理？？

**Comment by Sopage** [comment]
解决：将executeSwipeBackAnim中的实现
activity.overridePendingTransition(R.anim.bga_sbl_activity_swipeback_enter, R.anim.bga_sbl_activity_swipeback_exit);
修改为
 activity.overridePendingTransition(0, 0);

**Comment by wilsonssss** [comment]
@bingoogolapple 浩哥可以帮忙看看这个问题？ Android P 100% 重现的~ 感谢

**Comment by willsame** [comment]
@Sopage 修改后发现还是一样的，并没有解决 ，机型是 三星S8 8.0

**Comment by Sopage** [comment]
@willsame https://github.com/gongwen/SwipeBackLayout
我的在原生系统中解决了，其他的没有测试，你可以试试上面的那个怎么样
