### ISSUE TITLE
部分底部导航栏可以收起的手机会出现遮挡的bug

### ISSUE THREAD

**Issue by shenhuniurou** [bingoogolapple/BGASwipeBackLayout-Android#14]

**Comment by bingoogolapple** [comment]
一加手机？

**Comment by shenhuniurou** [comment]
华为Mate 7

**Comment by bingoogolapple** [comment]
能否克隆源码下来修复 https://github.com/bingoogolapple/BGASwipeBackLayout-Android/blob/master/library/src/main/java/cn/bingoogolapple/swipebacklayout/UIUtil.java 中的这个 bug，我这没底部导航栏可以收起的测试机，不好修复这个问题

![image](https://cloud.githubusercontent.com/assets/8949716/21742991/a8cde886-d534-11e6-8fb6-480558ba5338.png)

**Comment by bingoogolapple** [comment]
@shenhuniurou 改好了，方便加 qq 吗，我发个报给你试一下

**Comment by shenhuniurou** [comment]
@bingoogolapple 你好，昨天外出没有看到，刚才按照你改的试了已经正常了。谢谢
