### ISSUE TITLE
android9 滑动返回后屏幕会闪一下

### ISSUE THREAD

**Issue by leielyq** [bingoogolapple/BGASwipeBackLayout-Android#143]
咋办呢

**Comment by oarage** [comment]
的确有这个问题,9.0以下是好的,9.0的滑动返回后屏幕会闪一下.

**Comment by lotty520** [comment]
+1

**Comment by AbnerSC** [comment]
华为P20 EMUI9.0 Android9.0也是这个问题

**Comment by AbnerSC** [comment]
根据前面用户提供的问题原因，说一种临时解决方法，在自己的项目anim文件夹中新建两个同名文件，bga_sbl_activity_swipeback_enter.xml
bga_sbl_activity_swipeback_exit.xml，
内容都为
<?xml version="1.0" encoding="utf-8"?>
<translate xmlns:android="http://schemas.android.com/apk/res/android" />
取消动画效果

**Comment by ztind** [comment]
+1

**Comment by dawsonjiang** [comment]
> 根据前面用户提供的问题原因，说一种临时解决方法，在自己的项目anim文件夹中新建两个同名文件，bga_sbl_activity_swipeback_enter.xml
> bga_sbl_activity_swipeback_exit.xml，
> 内容都为
> 《?xml version="1.0" encoding="utf-8"?》
> 《translate xmlns:android="http://schemas.android.com/apk/res/android" /》
> 取消动画效果

也不起作用啊

**Comment by dawsonjiang** [comment]
我是通过根据demo把 initSwipeBackFinish();放在oncreate第一行的就好了

**Comment by qqiabc521** [comment]
+1

**Comment by willsame** [comment]
@AbnerSC 试了没用啊

**Comment by kennir** [comment]
+1

**Comment by leielyq** [comment]
@AbnerSC 该方法测试可以，谢谢，点赞

**Comment by w-g-b** [comment]
有用
