### ISSUE TITLE
在华为分屏导致好多问题

### ISSUE THREAD

**Issue by onexuan** [bingoogolapple/BGASwipeBackLayout-Android#147]
在华为分屏导致好多问题，一些滚动如Scrollview，RecyclerView无法滚动

**Comment by lanhuaguizha** [comment]
Please Call "setIsNavigationBarOverlap" method and set parameters "true" like this: mSwipeBackHelper.setIsNavigationBarOverlap(true)

**Comment by onexuan** [comment]
I had remove this lib now, because listview or RecyclerView has some bugs
