### ISSUE TITLE
demo 底部空白

### ISSUE THREAD

**Issue by liuhaiqiang** [bingoogolapple/BGASwipeBackLayout-Android#26]
您好，测试demo在htc e9pw手机上当隐藏虚拟按键后，则出现白色底，请问如何解决？

**Comment by Walkud** [comment]
遇到同样问题，在虚拟按键手机上会出现这种情况

**Comment by bingoogolapple** [comment]
反馈问题时请主动提供当前使用开源库的名字、开源库具体版本号、报错手机型号、报错手机系统版本以及错误日志

**Comment by bingoogolapple** [comment]
问题出在 https://github.com/bingoogolapple/BGASwipeBackLayout-Android/blob/master/library/src/main/java/cn/bingoogolapple/swipebacklayout/UIUtil.java 里的 checkDeviceHasNavigationBar 方法，没法判断你们那种可以动态设置底部导航栏是否可见的手机

我这里没那种手机不好 debug，@liuhaiqiang @Walkud  希望你俩能 git https://github.com/bingoogolapple/BGASwipeBackLayout-Android.git 克隆仓库下来调试一下看怎样处理

**Comment by Walkud** [comment]
我可能用的是比较老的版本，目前用最新的版本已经没发现该问题，谢谢

**Comment by jfjbYXY** [comment]
public static boolean checkDeviceHasNavigationBar(Activity activity) {
        boolean hasNavigationBar = false;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            String jixing = Build.MODEL.toLowerCase().trim();
            if (TextUtils.equals("Nexus 4".toLowerCase().trim(), jixing) || TextUtils.equals("huawei mt7-tl10".toLowerCase().trim(), jixing)) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
                    hasNavigationBar = true;
                else
                    hasNavigationBar = false;
            } else {
                hasNavigationBar = newCheckDeviceHasNavigationBar(activity);
            }
        } else {
            hasNavigationBar = oldCheckDeviceHasNavigationBar(activity);
        }
        return hasNavigationBar;
    }
如上，加入了机型判断和系统号判断，解决了底部被系统虚拟键盖住的问题。但是，但是，但是，新问题来了，隐藏了系统虚拟键后，界面底部没有顶到屏幕底端。
请问有什么合适的解决方案吗？

**Comment by bingoogolapple** [comment]
@jfjbYXY 你用的哪个版本？

**Comment by jfjbYXY** [comment]
@bingoogolapple huawei mt7-tl10这个机型的机器我们有两个，系统版本是不同的，在Android6.0上会被遮盖，但5.1 的不会。
再者，有太多位置的机型和系统组合可能会导致同样的问题，我们无法将所有组合都加入判断。
即使加了型号判断，太多类似华为的机器是可以隐藏虚拟键的。在把虚拟键隐藏后，下面依然会留白。
由于项目质量的因素，最终撤销了滑动退出的功能。

**Comment by jfjbYXY** [comment]
@bingoogolapple 发现您最近有更新，不知道有没有优化这个问题。当时为了添加判断，使用了您的源码，所以具体使用的是哪个tag版本，已经记不得了。回头再要加此功能时再看吧，谢谢您！

**Comment by tangjw** [comment]
我用的是模拟器测试的,只在 api 19发现这样的问题, 加了判断就行了: 
    
	if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
	    maxLayoutHeight -= UIUtil.getNavigationBarHeight(mActivity);
	}

**Comment by androidlli** [comment]
在api19的情况下下面会有navbar高度的空白

**Comment by bingoogolapple** [comment]
@androidlli 

3.如果发现某些手机上底部出现空白区域，麻烦打印以下信息新建 Issue 反馈

android.Build.VERSION.SDK_INT

android.Build.MODEL
