### ISSUE TITLE
用了ActivityOptionsCompat会有内存泄漏的问题

### ISSUE THREAD

**Issue by findvoid** [bingoogolapple/BGASwipeBackLayout-Android#27]
<img width="576" alt="qq20170122-0 2x" src="https://cloud.githubusercontent.com/assets/13435914/22179499/afc99c72-e090-11e6-8ce9-f22e358a3fa1.png">

**Comment by findvoid** [comment]
<img width="585" alt="2" src="https://cloud.githubusercontent.com/assets/13435914/22179506/dc245686-e090-11e6-87db-fa1c1d23e2f3.png">

**Comment by bingoogolapple** [comment]
怎样复现的？

用最新版试试

**Comment by bingoogolapple** [comment]
最新版引入 LeakCanary 后没检测出内存泄漏
