### ISSUE TITLE
这说明好难用啊，能不能简单明了一点？

### ISSUE THREAD

**Issue by limjiregister** [bingoogolapple/BGASwipeBackLayout-Android#29]
baseAcitity中没有用上toolBar，自己在各activity中使用toolbar。竟然 ，用了mSwipeBackHelper.forward(intent); 导致地面底部出现 透明，也就是可以看到 mainAcitity的界面。大约有八分之一的部位是透明的。怎么搞？？？

**Comment by bingoogolapple** [comment]
模拟器不管
