### ISSUE TITLE
背景色问题

### ISSUE THREAD

**Issue by shingohu** [bingoogolapple/BGASwipeBackLayout-Android#36]
当输入法弹出时,如果上一个界面背景色很显眼,如红色,此时可以看到上一个界面的颜色 很突兀,demo中mainActivity中背景改为红色,即可测试看到效果

**Comment by bingoogolapple** [comment]
开启滑动返回的 Activity 的主题要设置透明，但是该 Activity 布局文件的根控件需要设置一个背景色

https://github.com/bingoogolapple/BGASwipeBackLayout-Android/blob/705ca6612d5b72baa28929b3cd07b83c3e7e0e73/demo/src/main/res/layout/activity_recycler_index.xml
