### ISSUE TITLE
我设置了全屏显示，续承baseActivity后，度部的导航条不透明了

### ISSUE THREAD

**Issue by 1371030** [bingoogolapple/BGASwipeBackLayout-Android#41]
页面使用的是如下代码全屏，续承baseActivity后，度部的导航条不透明了
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    Window window = getWindow();
    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS
                              | WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
    window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                                                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                                                        | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
    window.setStatusBarColor(Color.TRANSPARENT);
    window.setNavigationBarColor(Color.TRANSPARENT);
}

**Comment by bingoogolapple** [comment]
Version 1.1.2 *(2017-10-13)*
----------------------------

* 初始化由「BGASwipeBackManager.getInstance().init(this)」改成「BGASwipeBackHelper.init(this)」
* 移除 BGASwipeBackManager 的 ignoreNavigationBarModels 方法
* 支持全屏、横屏
* 修复滑动释放逻辑错误
* 修复部分手机底部出现出现白色区域
