### ISSUE TITLE
底部白色

### ISSUE THREAD

**Issue by RichMoster** [bingoogolapple/BGASwipeBackLayout-Android#45]
SDK_INT:19 
MODEL:P7-L07
品牌：HUAWEI

华为 Ascend P7

**Comment by bingoogolapple** [comment]
麻烦加下 QQ 帮忙测试一下 496312716

**Comment by bingoogolapple** [comment]
用最新版

**Comment by RichMoster** [comment]
你好，在提出问题时候已经通过适配把p7-l07空白的问题解决了，貌似也只能去适配，没有好的办法，建议你去http://utest.qq.com/ 腾讯优测去测试各种机型，来适配；




------------------ 原始邮件 ------------------
发件人: "王浩";<notifications@github.com>;
发送时间: 2017年8月1日(星期二) 凌晨1:58
收件人: "bingoogolapple/BGASwipeBackLayout-Android"<BGASwipeBackLayout-Android@noreply.github.com>; 
抄送: "李鹏飞"<11748854@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [bingoogolapple/BGASwipeBackLayout-Android] 底部白色 (#45)




用最新版

**Comment by bingoogolapple** [comment]
`在提出问题时候已经通过适配把p7-l07空白的问题解决了` 通过什么方式适配的？依赖源码在 UIUtil 里添加的白名单吗？

**Comment by RichMoster** [comment]
是通过依赖源码在UIUtil里添加的白名单





------------------ 原始邮件 ------------------
发件人: "王浩";<notifications@github.com>;
发送时间: 2017年8月1日(星期二) 上午10:42
收件人: "bingoogolapple/BGASwipeBackLayout-Android"<BGASwipeBackLayout-Android@noreply.github.com>; 
抄送: "李鹏飞"<11748854@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [bingoogolapple/BGASwipeBackLayout-Android] 底部白色 (#45)




在提出问题时候已经通过适配把p7-l07空白的问题解决了 通过什么方式适配的？依赖源码在 UIUtil 里添加的白名单吗？

**Comment by bingoogolapple** [comment]
* 能否发一份你目前所收集的白名单，我在下一个版本中直接加到 Library 里。晚上回去我也到腾讯优测测一下
* 目前最新版增加了 BGASwipeBackManager.ignoreNavigationBarModels(Arrays.asList("底部出现空白区域的手机对应的 android.Build.MODEL")) 来添加白名单

**Comment by RichMoster** [comment]
目前还没有收集，只是在测试时候发现了p7有这个问题，还没有上线，而且时间有限，所以还没有大量测试，如果发现有问题的手机型号，我会通过邮件告知你。我抽时间看看能不能有别的办法。这个库还是很不错的，我会一直关注。




------------------ 原始邮件 ------------------
发件人: "王浩";<notifications@github.com>;
发送时间: 2017年8月1日(星期二) 上午10:49
收件人: "bingoogolapple/BGASwipeBackLayout-Android"<BGASwipeBackLayout-Android@noreply.github.com>; 
抄送: "李鹏飞"<11748854@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [bingoogolapple/BGASwipeBackLayout-Android] 底部白色 (#45)



 
能否发一份你目前所收集的白名单，我在下一个版本中直接加到 Library 里。晚上回去我也到腾讯优测测一下
 
目前最新版增加了 BGASwipeBackManager.ignoreNavigationBarModels(Arrays.asList("底部出现空白区域的手机对应的 android.Build.MODEL")) 来添加白名单

**Comment by bingoogolapple** [comment]
🤝

**Comment by jonenet** [comment]
小米mix2底部出现空白区域

**Comment by jonenet** [comment]
小米mix2底部出现空白区域
