### ISSUE TITLE
设置windowIsTranslucent=true后会跟activity的windowAnimationStyle切换动画冲突

### ISSUE THREAD

**Issue by zwonb** [bingoogolapple/BGASwipeBackLayout-Android#46]
android:windowIsTranslucent=true
设置上面这个属性
 android:activityOpenEnterAnimation@anim/activity_enter
     android:activityCloseExitAnimation@anim/activity_exit
下面这两个失效
        android:activityOpenExitAnimation@anim/activity_hide
        android:activityCloseEnterAnimation@anim/activity_show

**Comment by bingoogolapple** [comment]
按文档和 Demo 里的来

* 开启滑动返回的 Activity 主题透明
* 开启滑动返回的 Activity 的 onBackPressed 方法里调用 mSwipeBackHelper.backward()，该方法已经带上动画了

https://github.com/bingoogolapple/BGASwipeBackLayout-Android/blob/705ca6612d5b72baa28929b3cd07b83c3e7e0e73/demo/src/main/java/cn/bingoogolapple/swipebacklayout/demo/activity/BaseActivity.java

https://github.com/bingoogolapple/BGASwipeBackLayout-Android/blob/705ca6612d5b72baa28929b3cd07b83c3e7e0e73/library/src/main/java/cn/bingoogolapple/swipebacklayout/BGASwipeBackHelper.java
