### ISSUE TITLE
开启微信返回样式，有时候当前Activity也会和底部Activity一样向左偏移1/3

### ISSUE THREAD

**Issue by xiejingwen** [bingoogolapple/BGASwipeBackLayout-Android#48]
如题

**Comment by xiejingwen** [comment]
![lpl1aupw 11rn svx5 k0c9](https://user-images.githubusercontent.com/13871875/28405012-22fd948c-6d5e-11e7-8c1f-3192d763ec38.png)

**Comment by zzmgoing** [comment]
是有这个问题，楼主解决了吗

**Comment by bingoogolapple** [comment]
Version 1.1.2 *(2017-10-13)*
----------------------------

* 初始化由「BGASwipeBackManager.getInstance().init(this)」改成「BGASwipeBackHelper.init(this)」
* 移除 BGASwipeBackManager 的 ignoreNavigationBarModels 方法
* 支持全屏、横屏
* 修复滑动释放逻辑错误
* 修复部分手机底部出现出现白色区域
