### ISSUE TITLE
底部出现空白区域的手机对应的 android.Build.MODEL

### ISSUE THREAD

**Issue by bingoogolapple** [bingoogolapple/BGASwipeBackLayout-Android#51]
### 如果发现某些手机上底部出现空白区域，麻烦打印以下信息反馈到当前 Issue 中

```
android.Build.VERSION.SDK_INT

android.Build.MODEL
```

可以通过 BGASwipeBackManager.ignoreNavigationBarModels(Arrays.asList("底部出现空白区域的手机对应的 android.Build.MODEL")) 来临时解决该问题

目前已发现机型
* Nexus 4
* H60-L01
* P7-L07
* MT7-UL00
* HUAWEI P7-L07
* OPPO R7s
* Xiaomi HM Note 1S

**Comment by lxmy** [comment]
你好，测试发现华为P7手机底部出现空白区域

版本 cn.bingoogolapple:bga-swipebacklayout:1.1.0
Build.VERSION.SDK_INT=19
Build.MODEL=HUAWEI P7-L07

**Comment by instanceofz** [comment]
你好，测试发现OPPO R7s手机底部出现空白区域

版本 cn.bingoogolapple:bga-swipebacklayout:1.1.0
Build.VERSION.SDK_INT=19
Build.MODEL=OPPO R7s

**Comment by 5bo** [comment]
你好，测试发现红米Note手机底部出现空白区域
Build.VERSION.SDK_INT=19
Build.MODEL=Xiaomi HM Note 1S

**Comment by bingoogolapple** [comment]
@lxmy @instanceofz @5bo 谢谢反馈，最新版本 v1.1.1 已经在 library 中添加这三个机型到白名单中了

**Comment by instanceofz** [comment]
你好，测试发现华为P7手机底部出现空白区域

版本 cn.bingoogolapple:bga-swipebacklayout:1.1.1
Build.VERSION.SDK_INT=19
Build.MODEL=HUAWEI P7-L09

发现一个规律，都是Build.VERSION.SDK_INT=19，要不要统一做下19的适配呢？

**Comment by instanceofz** [comment]
你好，测试发现华为P7手机底部出现空白区域

版本 cn.bingoogolapple:bga-swipebacklayout:1.1.1
Build.VERSION.SDK_INT=22
Build.MODEL=LG-D855

这次这个不是19了，但是2k屏幕， 使用BGASwipeBackManager.ignoreNavigationBarModels(Arrays.asList(models));后，底下空白被原来的布局覆盖，原来的布局不见一截。

**Comment by zhudongya123** [comment]
Build.VERSION.SDK_INT=23
Build.MODEL=E6683

**Comment by tongtian00** [comment]
你好，测试发现两部华为手机底部出现空白区域

版本 cn.bingoogolapple:bga-swipebacklayout:1.1.1

Build.VERSION.SDK_INT=19
Build.MODEL=HUAWEI G7-TL00

Build.VERSION.SDK_INT=19
Build.MODEL=PE-CL00

**Comment by brightpoplar** [comment]
你好，测试两部手机：
版本 cn.bingoogolapple:bga-swipebacklayout:1.1.1

索尼：手机 有 底部导航条
Build.VERSION.SDK_INT = 19
Build.MODEL = L55t

华为：手机 没有 底部导航条
Build.VERSION.SDK_INT = 17
Build.MODEL = H30-T10

@@@::
cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout.onMeasure(int widthMeasureSpec, int heightMeasureSpec){
		......
		// ======================== 新加的 START ======================
		// 这里：如果放开 【索尼】手机底部出现空白区域，注掉则不会出现；华为没有此问题
		//       @：个人建议，楼主后期对此问题优化的话，从导航条入手
		// maxLayoutHeight -= UIUtil.getNavigationBarHeight(mActivity);
                // ======================== 新加的 END ========================
		......
	}

**Comment by yuer8087** [comment]
发现华为手机出现该问题
Build.VERSION.SDK_INT=19
Build.MODEL=PE-TL10

**Comment by huohuo5753** [comment]
发现华为手机出现该问题
Build.MODEL = PE-UL00
Build.VERSION.SDK_INT = 19

**Comment by huohuo5753** [comment]
此问题的原因我分析了一下，问题定位BGASwipeBackLayout.class类中的onMeasure（）方法中；

private int getScreenHeight()
    {   int screenHeight = 0;
        Display display = ((Activity)getContext()).getWindowManager().getDefaultDisplay();
        DisplayMetrics dm = new DisplayMetrics();
        @SuppressWarnings("rawtypes")
        Class c;
        try {
            c = Class.forName("android.view.Display");
            @SuppressWarnings("unchecked")
            Method method = c.getMethod("getRealMetrics",DisplayMetrics.class);
            method.invoke(display, dm);
            screenHeight=dm.heightPixels;
        }catch(Exception e){
            e.printStackTrace();
        }
        return screenHeight;
    }
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int widthMode = MeasureSpec.getMode(widthMeasureSpec);
        int widthSize = MeasureSpec.getSize(widthMeasureSpec);
        int heightMode = MeasureSpec.getMode(heightMeasureSpec);
        //int heightSize = MeasureSpec.getSize(heightMeasureSpec);
        int heightSize = getScreenHeight();
       。。。。。                } 

heightSize高度的计算问题，通过debug发现，正常的手机最后heightSize的值为整个屏幕的高度，出现白屏的手机获取的heightSize的值为不包含虚拟键盘高度的有效屏幕高度（比如整屏1920的，此时获取到的值是1814）；
所以我的解决思路是heightSize的值必须获取为整个屏幕的高度；

个人观点，请作者看是否可以作为解决方案；

**Comment by bingoogolapple** [comment]
Version 1.1.2 *(2017-10-13)*
----------------------------

* 初始化由「BGASwipeBackManager.getInstance().init(this)」改成「BGASwipeBackHelper.init(this)」
* 移除 BGASwipeBackManager 的 ignoreNavigationBarModels 方法
* 支持全屏、横屏
* 修复滑动释放逻辑错误
* 修复部分手机底部出现出现白色区域

**Comment by jeesezh** [comment]
你好，锤子坚果pro2也出现空白问题
cn.bingoogolapple:bga-swipebacklayout:1.1.8
Build.VERSION.SDK_INT=25
Build.MODEL=OS105

**Comment by renjianan** [comment]
锤子坚果pro2也出现空白问题 ，导航栏隐藏的情况下，UIUtil.isNavigationBarVisible(Activity activity)返回true

**Comment by finalrose7** [comment]
你好，锤子坚果pro2也出现空白问题
cn.bingoogolapple:bga-swipebacklayout:1.1.8
Build.VERSION.SDK_INT=25
Build.MODEL=OS105
