### ISSUE TITLE
BGASwipeBackLayout中的mMoveState变量，导致关闭逻辑错误

### ISSUE THREAD

**Issue by yangbo637829** [bingoogolapple/BGASwipeBackLayout-Android#53]
BGASwipeBackLayout中的onPanelDragged方法里面部分代码导致右滑一部分之后再左滑，页面还是关闭了。引起问题的代码：
`        float curOffsetDelta = mSlideOffset - lastSlideOffset;
        if (mMoveState == MOVE_STATE_RIGHT) {
            if (curOffsetDelta < mLastOffsetDelta) {
                curOffsetDelta = mLastOffsetDelta;
                mSlideOffset = lastSlideOffset + curOffsetDelta;
                mSlideOffset += 0.05f;
                if (mSlideOffset > 1.0f) {
                    mSlideOffset = 1.0f;
                }
            } else {
                mLastOffsetDelta = curOffsetDelta;
            }
        }
`
我在本地尝试去掉mLastOffsetDelta和mMoveState相关的逻辑处理，发现没有出问题。所以请问下，这部分的逻辑是不是应该去掉会好些。

**Comment by bingoogolapple** [comment]
👌 下班回去搞
