### ISSUE TITLE
popupwindow

### ISSUE THREAD

**Issue by lsy-itsprots** [bingoogolapple/BGASwipeBackLayout-Android#55]
activity中设置透明之后，如果里面包含一个popupwindow并且在pop显示的时候设置 getWindow().setAttributes(lp)透明度之后会看到上一个界面

**Comment by bingoogolapple** [comment]
试试最新版还有没有这个问题

**Comment by bingoogolapple** [comment]
最新版已经支持非透明主题滑动返回
