### ISSUE TITLE
Activity全屏的问题

### ISSUE THREAD

**Issue by xuekaiqi** [bingoogolapple/BGASwipeBackLayout-Android#56]
当我这是了webview播放视频，采用第三方的腾讯x5进行全屏播放，当我webviewActivity 切换全屏的时候  我的**MainActivity**生命周期会重新走一遍，导致弹出升级对话框（当有升级提示时候） 打印发现MainActivity 的 Oncreat重新走了一遍   而不是webviewActivity 的 Oncreat

**Comment by bingoogolapple** [comment]
这是透明主题导致的，但这个滑动返回库又必须要设置当前 Activity 为透明主题，暂时没有什么好的解决方案。

你可以在 MainActivity 检测升级的地方判断一下 MainActivity 是否为栈顶 Activity

**Comment by bingoogolapple** [comment]
方案一：升级到最新版，已支持非透明主题滑动返回，将 WebViewActivity 设置成非透明主题
方案二：在 MainActivity 检测升级的地方判断一下 MainActivity 是否为栈顶 Activity
