### ISSUE TITLE
关于阴影

### ISSUE THREAD

**Issue by Sonnyzoom** [bingoogolapple/BGASwipeBackLayout-Android#6]
一个很不错的库，看了这么多，终于看见一个比较满意的了。只是滑动返回阴影效果有点重，如果可以自定义阴影深度就好了。

**Comment by bingoogolapple** [comment]
阴影太深？

目前可以通过在你自己 moudle 的 drawable 目录下放置名字叫 bga_swipebacklayout_shadow.9.png 的替换

后期我改成可配置或者 TintColor

**Comment by bingoogolapple** [comment]
最新版 v1.0.2 增加了 setShadowResId 方法
