### ISSUE TITLE
隐藏NavigationBar全屏的时候，底部白色

### ISSUE THREAD

**Issue by shicaiD** [bingoogolapple/BGASwipeBackLayout-Android#60]
- 设置View.SYSTEM_UI_FLAG_HIDE_NAVIGATION后，NavigationBar隐藏了，但还有白色区域。

- 我目前解决方案是通过反射UIUtil拿到NO_NAVIGATION_BAR_MODEL_SET，添加mode白名单，onDestroy的时候还是通过反射移除mode白名单。

- 希望能有更好的解决方案😃

**Comment by bingoogolapple** [comment]
用最新版
