### ISSUE TITLE
弱弱的问一下怎么更换打开新页面的动画，用了滑动返回之后打开新页面的动画设置不管用了

### ISSUE THREAD

**Issue by GerogeHotz** [bingoogolapple/BGASwipeBackLayout-Android#62]

**Comment by bingoogolapple** [comment]
是替换所有的吗？

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/31849565-fc07f1de-b609-11e7-97a5-ef4fb6be742e.png)

在你自己项目的 anim 目录下添加同名的 bga_sbl_activity_forward_enter.xm 和 bga_sbl_activity_forward_exit.xml 来自定义打开新页面的动画
