### ISSUE TITLE
非透明主题滑动返回时仍然会有闪屏效果

### ISSUE THREAD

**Issue by AttackOnDobby** [bingoogolapple/BGASwipeBackLayout-Android#65]
版本v1.1.3，机型nexus 6p，系统6.0.1

**Comment by bingoogolapple** [comment]
用的非透明主题模式，但是某个界面用了透明主题模式时滑动返回结束时闪屏？

**Comment by AttackOnDobby** [comment]
对的，假设A是透明主题，B是非透明主题，从A滑动到B或者从B滑动到A都会闪

**Comment by findvoid** [comment]
我用了最新版本1.1.6这个问题还是会出现,上一个页面A有surfaceView滑动到B然后从B滑动到A,surfaceView会闪,A是不透明主题,B是透明主题,APP初始化是这样的:BGASwipeBackHelper.init(this, null);

**Comment by bingoogolapple** [comment]
B 必须是透明主题？

**Comment by findvoid** [comment]
嗯 B也是继续跳转C,C返回的话,B不是透明主题就看不到B了 @bingoogolapple

**Comment by xiang473535976** [comment]
我也是这样的问题   上层是webview页面 返回 就会闪屏 @findvoid @bingoogolapple

**Comment by bingoogolapple** [comment]
最新版支持非透明主题了，把 B 改成非透明主题试试

**Comment by xiang473535976** [comment]
@bingoogolapple  1.我所有的都是非透明  上层页面有webview    返回   webview会闪一下  应该是重新加载了
2  我改成非透明模式  但是有刷新功能的刷新控件 上拉的时候     底部会显示上层的页面   windowBackground设置成透明的

**Comment by xiang473535976** [comment]
主要是设置了这个属性  ！！   请帮忙看看
@bingoogolapple
