### ISSUE TITLE
Android 4.4.4下，app内容被navigationbar覆盖

### ISSUE THREAD

**Issue by ShshyDevooo** [bingoogolapple/BGASwipeBackLayout-Android#69]
![eb66a188fdcea685fdbb1d8fd0e9a7e9](https://user-images.githubusercontent.com/9620338/31929031-defdc77e-b8cc-11e7-8ad4-691b2c5daff7.jpg)
如图，demo中滚动条已经滚动到底部，但是按钮仍然被覆盖，调用setIsNavigationBarOverlap该方法设置true和false无效，求解答，谢谢！

**Comment by a616551624** [comment]
机型Mx3

**Comment by a616551624** [comment]
机型Mx3，目前使用的版本为1.1.4，底部仍然出现空白区域

**Comment by a616551624** [comment]
机型Mx3，目前使用的版本为1.1.4

**Comment by a616551624** [comment]
问题好像出现在UIUtil的checkDeviceHasNavigationBar()方法中,当前手机有NavigationBar的情况下，通过该方法获取的返回值为false。

**Comment by bingoogolapple** [comment]
没你那款测试机，麻烦依赖源码，将 demo 直接依赖 library 单独适配下你那款手机

```gradle
compile project(':library')
```

**Comment by a616551624** [comment]
魅族3，不是NavigationBar是smartbar，是否考虑适配smartbar？

**Comment by bingoogolapple** [comment]
我这边一台魅族手机都没有，要不你尝试一下适配 smartbar
