### ISSUE TITLE
普通滑动返回的样式问题

### ISSUE THREAD

**Issue by AttackOnDobby** [bingoogolapple/BGASwipeBackLayout-Android#70]
1. 在设置成普通返回样式的时候，发现底部Activity视图在跟随移动，如何能做到底部Activity固定不动，仅上层Activity滑动返回

2. 在开启滑动返回功能之后，调用Activity的finish方法会自动左滑返回，如何能设置它按原生的转场动画方式返回

**Comment by bingoogolapple** [comment]
* 问题1用最新版
* 问题2和手机系统有关，我试了不调用 mSwipeBackHelper.backward()，调用 Activity 的 finish 方法后
  * Nexus 5 上原生转场动画就是上下
  * 华为手机上原生转场动画就是左右

如果想在调用 Activity 的 finish 方法后每台手机上保持一种同一种转场动画，建议在代码里统一添加
