### ISSUE TITLE
呼唤国产手机导航栏白条、内容遮盖的朋友前来助攻

### ISSUE THREAD

**Issue by xiaobaDev** [bingoogolapple/BGASwipeBackLayout-Android#74]
出现白条、遮盖，出现这个问题的根源在于厂家自己实现了navigationBar状态的管理，导致我们用系统的状态栏高度计算出问题，出问题的在oppo R7Plus。这款手机，导航条逻辑被厂商魔改过后，显示、隐藏、flag检测都出了问题，导致作者的代码在这款上面会出现白条

安卓翻了下源码，在5.0以上的机型，decoverView子View有个导航栏背景色View,ID叫navigationBarBackground；现在我有了解决办法，就是检测厂家自己定义的导航条View，我们自己做处理

[8.0源码地址](http://androidxref.com/8.0.0_r4/xref/frameworks/base/core/java/com/android/internal/policy/DecorView.java)

已知oppo R9Plus、华为ALE-TL100、华为PLK-TL10H的 navigationBar的ID都叫navigationBarBackground

大家可以打开demo，然后把View的节点打印出来查看下
类似的魅族老款的flyme也可以这么做

**Comment by xiaobaDev** [comment]
r9 plus的导航条收起、关闭，获取的导航条高度都是一个固定的数值，比如200；收起的时候，多减去了200的高度，导致内容出现了白条；这个时候，这个View的Visibility是inVisibile，我们可以根据这个状态来判断不去减200高度；
同理比如魅族的老款手机有smartBar的，我们拿到smartBar的高度后，就可以正确减去高度，避免出现遮盖的情况

**Comment by xiaobaDev** [comment]
总体思路是，国产定制的导航条能找到，就用它来做导航条数据源；否则使用作者的通用处理方案（作者的方案在新机型上试过没啥问题，有华为、摩托罗拉）

**Comment by bingoogolapple** [comment]
@xiaobaDev 你那边出现导航栏白条是用的最新版本 v1.1.5 吗？

**Comment by xiaobaDev** [comment]
是最新的，这个和你版本其实没啥关系了，有些Rom的NavigationBar高度，用你那套算法不准

**Comment by a616551624** [comment]
请问你说的打开demo，然后把View的节点打印出来查看下。请问如何打印？

**Comment by xiaobaDev** [comment]
用android studio 运行demo程序，在Ide的底部栏目里找到 android Monitor，点开；再找到左边的Layout Inspector，点击下，等待android studio 打印出节点，然后找到ID的属性即可

**Comment by a616551624** [comment]
魅族3 Layout Inspector下看不到smartbar

**Comment by a616551624** [comment]
![20171103142207](https://user-images.githubusercontent.com/9620338/32362330-59e85cb4-c0a3-11e7-9300-a1f30cc36f2c.png)

**Comment by xiaobaDev** [comment]
这个只能稍等下了，我先把主流思路实现掉，再去做这smartBar的适配

**Comment by xiaobaDev** [comment]
这个我改完了，但是为了兼容部分国产机型而做的改动比较大，等我们的产品稳定运行一个版本，再推commit
大体思路就是本文所描述的

**Comment by ronanhardiman** [comment]
@xiaobaDev 请问这个稳定了么，遇到类似的问题。
