### ISSUE TITLE
滑动返回导致布局下移

### ISSUE THREAD

**Issue by AttackOnDobby** [bingoogolapple/BGASwipeBackLayout-Android#78]
在有底部虚拟键Navigation Bar的机器上，从主界面A进入子界面 B的过程中，设置B的`isSupportSwipeBack`为true。其中A的布局为：

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context="com.slide.demo.MainActivity">
    
        <TextView
            android:id="@+id/tv_demo"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:layout_gravity="bottom"
            android:background="@android:color/darker_gray"
            android:gravity="center"
            android:text="@string/app_name"
            android:textSize="20sp" />
    
    </LinearLayout>

此时如果从B滑动返回到A，TextView会下沉虚拟Navigation Bar的高度。经排查，可能与TextView的layout_gravity属性设为bottom有关。

请问有没有合适的方案可解决这个问题

**Comment by diewu0421** [comment]
我也遇到这个问题了，确实是只在有有导航栏的机型上出现了，目前还没有解决。

**Comment by findvoid** [comment]
设置activity主题

**Comment by AttackOnDobby** [comment]
@findvoid 如何设置？设置为什么主题？

**Comment by findvoid** [comment]
demo中的透明主题

**Comment by AttackOnDobby** [comment]
@findvoid  透明主题会和我的工程项目产生冲突，如果在非透明主题模式下，要如何解决？

**Comment by yueqch** [comment]
我也有一样的问题 @bingoogolapple

**Comment by bingoogolapple** [comment]
开源库用的哪个版本？什么机型？贴一下布局文件

**Comment by AttackOnDobby** [comment]
lib版本为1.1.6，机器是google nexus 6p，系统6.0.1，布局文件见帖子描述，如果还不够清楚，可以下载demo [https://github.com/AttackOnDobby/SwipeDemo](url)，经验证在6.0模拟器中也可以复现该问题

**Comment by AttackOnDobby** [comment]
@bingoogolapple lib版本为1.1.6，机器是google nexus 6p，系统6.0.1，布局文件见帖子描述，如果还不够清楚，可以下载demo https://github.com/AttackOnDobby/SwipeDemo，经验证在6.0模拟器中也可以复现该问题

**Comment by findvoid** [comment]
1.1.6 华为荣耀带虚拟按键
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/rl_window"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/custom_attr_app_status_bar_bg">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/custom_attr_app_title_layout_bg"
        app:popupTheme="@style/ToolbarPopupTheme"
        app:theme="@style/ToolBarTheme">

        <TextView
            android:id="@+id/center_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:ellipsize="end"
            android:maxEms="12"
            android:singleLine="true"
            android:textColor="?attr/custom_attr_main_title_color"
            android:textSize="16sp"
            android:textStyle="bold" />
    </android.support.v7.widget.Toolbar>

    <FrameLayout
        android:id="@+id/contentContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/bottomBar"
        android:layout_below="@id/toolbar"
        android:background="@android:color/background_light" />

    <android.support.design.widget.BottomNavigationView
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="?attr/custom_attr_app_bottom_bg_color"
        app:itemIconTint="@drawable/selector_bottom_nav_item"
        app:itemTextColor="@drawable/selector_bottom_nav_item"
        app:menu="@menu/bottombar_tabs" />
</RelativeLayout>

**Comment by yueqch** [comment]
应该是带底部虚拟键盘的机型都有这个问题。按权重设置的布局或android:layout_gravity="bottom"，底部最后一个控件，从一个新页面滑动返回此页面，这个控件会下移到虚拟键盘的后面，也就是说忽略了虚拟键盘的高度。 @bingoogolapple

**Comment by 0924chun** [comment]
同一种情况 从主页打开B页面 B侧滑返回 会导致首页底部的布局被导航栏遮盖

**Comment by HikariNoSenritsu** [comment]
侧滑返回时首页底部布局被导航栏遮住+1。并且在带有可隐藏虚拟导航栏的机型中还会在布局底部生成一个导航栏高度的白色遮罩（见截图），测试机型三星S8，第一个截图是我写的demo中的截图，由于背景是灰色的，所以底部的白色遮罩很明显。后面两个是BGASwipeBackLayout DEMO中的界面，可以明显的看到列表底部被遮罩顶上去了一截。

---
![1091512718243_ pic_hd](https://user-images.githubusercontent.com/12892944/33755974-3faf6b2a-dc2e-11e7-9b57-3d144a040376.jpg)
---
![1111512718389_ pic](https://user-images.githubusercontent.com/12892944/33755975-3fed1e16-dc2e-11e7-9c2a-403bb8107a7b.jpg)
---
![1101512718358_ pic](https://user-images.githubusercontent.com/12892944/33755976-402831ea-dc2e-11e7-9fa9-7f87250e3612.jpg)

**Comment by yangtuhua** [comment]
+1。最新版发布版本还没有解决这个问题

**Comment by bingoogolapple** [comment]
#91
