### ISSUE TITLE
重新下载库的问题

### ISSUE THREAD

**Issue by findvoid** [bingoogolapple/BGASwipeBackLayout-Android#80]
为什么这个库我每次打开项目或者重构gradle文件都需要重新下载,请问如何取消

**Comment by bingoogolapple** [comment]
可能和 gradle 插件有关
1.1.7 之前是 gradle 2.x 的插件
1.1.7 开始是 gradle 3.x 的插件

我本地用 gralde 3.0.1 的插件没复现
![image](https://user-images.githubusercontent.com/8949716/34222942-5c8de23e-e5f8-11e7-8f0f-1fe5188e85f3.png)
