### ISSUE TITLE
redmiNote3 显示问题

### ISSUE THREAD

**Issue by longtaoge** [bingoogolapple/BGASwipeBackLayout-Android#9]
小米手机 偶尔会露出桌面

![](https://github.com/longtaoge/BGASwipeBackLayout-Android/blob/master/demo/image//XLB20161229130941.jpg)
![](https://github.com/longtaoge/BGASwipeBackLayout-Android/blob/master/demo/image/XLB20161229130957.jpg)

**Comment by bingoogolapple** [comment]
[StatusBarUtil](https://github.com/laobie/StatusBarUtil) 结合 CoordinatorLayout 一起使用时有这个问题，已通知该库的作者 @laobie

**Comment by laobie** [comment]
@longtaoge 跟进中

**Comment by bingoogolapple** [comment]
@laobie 有个现象是 demo 里 TestActivity 里的 ViewPager 切换时重新调一次 StatusBarUtil.setColorForSwipeBack 方法这个问题又好了

**Comment by laobie** [comment]
@bingoogolapple 好的 我留意下 我先写代码
